/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OptometryRouteImport } from './routes/optometry'
import { Route as OptometristLimpopoRouteImport } from './routes/optometrist-limpopo'
import { Route as MedicalServicesRouteImport } from './routes/medical-services'
import { Route as MedicalPracticeRouteImport } from './routes/medical-practice'
import { Route as GpGlencowieRouteImport } from './routes/gp-glencowie'
import { Route as DoctorJaneFurseRouteImport } from './routes/doctor-jane-furse'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const OptometryRoute = OptometryRouteImport.update({
  id: '/optometry',
  path: '/optometry',
  getParentRoute: () => rootRouteImport,
} as any)
const OptometristLimpopoRoute = OptometristLimpopoRouteImport.update({
  id: '/optometrist-limpopo',
  path: '/optometrist-limpopo',
  getParentRoute: () => rootRouteImport,
} as any)
const MedicalServicesRoute = MedicalServicesRouteImport.update({
  id: '/medical-services',
  path: '/medical-services',
  getParentRoute: () => rootRouteImport,
} as any)
const MedicalPracticeRoute = MedicalPracticeRouteImport.update({
  id: '/medical-practice',
  path: '/medical-practice',
  getParentRoute: () => rootRouteImport,
} as any)
const GpGlencowieRoute = GpGlencowieRouteImport.update({
  id: '/gp-glencowie',
  path: '/gp-glencowie',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorJaneFurseRoute = DoctorJaneFurseRouteImport.update({
  id: '/doctor-jane-furse',
  path: '/doctor-jane-furse',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/doctor-jane-furse': typeof DoctorJaneFurseRoute
  '/gp-glencowie': typeof GpGlencowieRoute
  '/medical-practice': typeof MedicalPracticeRoute
  '/medical-services': typeof MedicalServicesRoute
  '/optometrist-limpopo': typeof OptometristLimpopoRoute
  '/optometry': typeof OptometryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/doctor-jane-furse': typeof DoctorJaneFurseRoute
  '/gp-glencowie': typeof GpGlencowieRoute
  '/medical-practice': typeof MedicalPracticeRoute
  '/medical-services': typeof MedicalServicesRoute
  '/optometrist-limpopo': typeof OptometristLimpopoRoute
  '/optometry': typeof OptometryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/doctor-jane-furse': typeof DoctorJaneFurseRoute
  '/gp-glencowie': typeof GpGlencowieRoute
  '/medical-practice': typeof MedicalPracticeRoute
  '/medical-services': typeof MedicalServicesRoute
  '/optometrist-limpopo': typeof OptometristLimpopoRoute
  '/optometry': typeof OptometryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/blog'
    | '/contact'
    | '/doctor-jane-furse'
    | '/gp-glencowie'
    | '/medical-practice'
    | '/medical-services'
    | '/optometrist-limpopo'
    | '/optometry'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/blog'
    | '/contact'
    | '/doctor-jane-furse'
    | '/gp-glencowie'
    | '/medical-practice'
    | '/medical-services'
    | '/optometrist-limpopo'
    | '/optometry'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/blog'
    | '/contact'
    | '/doctor-jane-furse'
    | '/gp-glencowie'
    | '/medical-practice'
    | '/medical-services'
    | '/optometrist-limpopo'
    | '/optometry'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BlogRoute: typeof BlogRoute
  ContactRoute: typeof ContactRoute
  DoctorJaneFurseRoute: typeof DoctorJaneFurseRoute
  GpGlencowieRoute: typeof GpGlencowieRoute
  MedicalPracticeRoute: typeof MedicalPracticeRoute
  MedicalServicesRoute: typeof MedicalServicesRoute
  OptometristLimpopoRoute: typeof OptometristLimpopoRoute
  OptometryRoute: typeof OptometryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/optometry': {
      id: '/optometry'
      path: '/optometry'
      fullPath: '/optometry'
      preLoaderRoute: typeof OptometryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/optometrist-limpopo': {
      id: '/optometrist-limpopo'
      path: '/optometrist-limpopo'
      fullPath: '/optometrist-limpopo'
      preLoaderRoute: typeof OptometristLimpopoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/medical-services': {
      id: '/medical-services'
      path: '/medical-services'
      fullPath: '/medical-services'
      preLoaderRoute: typeof MedicalServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/medical-practice': {
      id: '/medical-practice'
      path: '/medical-practice'
      fullPath: '/medical-practice'
      preLoaderRoute: typeof MedicalPracticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gp-glencowie': {
      id: '/gp-glencowie'
      path: '/gp-glencowie'
      fullPath: '/gp-glencowie'
      preLoaderRoute: typeof GpGlencowieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor-jane-furse': {
      id: '/doctor-jane-furse'
      path: '/doctor-jane-furse'
      fullPath: '/doctor-jane-furse'
      preLoaderRoute: typeof DoctorJaneFurseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BlogRoute: BlogRoute,
  ContactRoute: ContactRoute,
  DoctorJaneFurseRoute: DoctorJaneFurseRoute,
  GpGlencowieRoute: GpGlencowieRoute,
  MedicalPracticeRoute: MedicalPracticeRoute,
  MedicalServicesRoute: MedicalServicesRoute,
  OptometristLimpopoRoute: OptometristLimpopoRoute,
  OptometryRoute: OptometryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
